%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 

imu: 1       
num_of_stereo_cam: 1
num_of_mono_cam:   0

imu_topic:    "/indemind/imu"
image0_topic: "/indemind/left/image"
image1_topic: "/indemind/right/image"
image2_topic: ""
image3_topic: ""
output_path:  "~/output"   

cam0_calib: "left_mei.yaml"
cam1_calib: "right_mei.yaml"
cam2_calib: ""
cam3_calib: ""

image_width:  640
image_height: 400
   
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix #cam0 coordinate under body coordinate
   rows: 4
   cols: 4
   dt: d
   data: [  0.999989 ,  0.00463936, -0.000940716 ,-0.0594296,
          -0.0046432   ,  0.999981 , -0.00411734  ,0.0103112,
          0.000921596 ,  0.00412166   ,  0.999991,  0.0197695, 
          0. ,     0.   , 0. ,1  ]



body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.999983 ,  0.00090524  , 0.00570149          ,0.049494,
          -0.000850023  ,   0.999953  ,-0.00967952          ,0.014365,
          -0.00570999  , 0.00967451  ,   0.999937       ,0.016167,
          0.          , 0.       ,0.          ,1.   ]

#Multiple thread support
multiple_thread: 1

#fish eye parameters
fish_eye_mask_radius: 0 # 自动生成
#fish_eye_mask_path: "/home/jon/code/ubt_code/mult_mono_vins/vins_mult_ws/src/VINS-Fusion/config/mask.jpg"

#feature traker paprameters
max_cnt: 70            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
#min_dist: 20           # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.02   # max solver itration time (ms), to guarantee real time
max_num_iterations: 6   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2  #0.2         # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001       # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8015         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.002  # -0.007230                  # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 1        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/jon/code/data/1217/"    # save and load path
save_image: 0                       # save image in pose graph for visualization prupose; you can close this function by setting 0 
add_data_base: 0            #检测回环时是否将当前帧加入到数据库中
min_loop_num: 10              # 匹配上的特征点, 后面还会进行pnp剔除
fast_th:  10                  # 20 ~ 300个 10 ~ 500个


#line
use_line: 0
pl_slam: 0
shuang_mu: 0